### PR TITLE
Bump version to 1.4.0

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by nseidle** [comment]
Thank you for this but the Arduino lib scraper is pretty particular. If I merge your changes and do a release using the same v1.4.0 version tag the Arduino scraper may get confused by the change in file but lack of change of release number. If you need to modify a file you need to bump all versions:

* Mod and push ver bump to library.properties to v1.5.0 (or whatever)
* Mod and push ver bump to jason file to v1.5.0

I'll merge then do a release.

It's tedious but it's what we have to play by for the Arduino lib manager to work.

**Comment by ivankravets** [comment]
No need to add a new tag. Just merge this PR and PlatformIO will automatically find proper release tag.

**Comment by nseidle** [comment]
Ah! Got it. Thanks for explaining it to me.

**Comment by ivankravets** [comment]
Thanks, Nathan!

**Pull request merged**
